# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'show-me-aui' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for show-me-aui
  pod 'SnapKit', '~> 3.2.0'
  pod 'Alamofire', '~> 4.4'
  pod 'MRProgress'
  pod 'IQKeyboardManagerSwift'
  pod 'UIView+Shake'
  pod 'SQLite.swift', '~> 0.11.3'
  pod 'SwiftyJSON'
  pod 'TouchVisualizer', '~>2.0.1'
end
